### ISSUE TITLE
CI failed after upgrade to Xcode 11, seems rendering is slightly changed

### ISSUE THREAD

**Issue by liuxuan30** [uber/ios-snapshot-test-case#102]
Hi there,

Please take a look at https://github.com/danielgindi/Charts/pull/4153

I found that, the iamge difference is increased after upgrading to Xcode11. so far I only see the black/grey color different on the same pixel from diff tool (image screenshot please refer #4153).

I'm not sure if this is caused by iOS 13 SDK, or this framework?

I'm not very willing to increase the tolerance rate. If there is nothing we can do, the last resort is to rebuild the images. But before that, I would like to query first. Thank you!

**Comment by liuxuan30** [comment]
a more obvious one:
![image](https://user-images.githubusercontent.com/4375169/65412860-ae895180-de22-11e9-9053-c0cdd8e25b5d.png)
the bold black text is the image diff by Kaleidoscope

**Comment by liuxuan30** [comment]
playing the animation from first image to second one in Kaleidoscope (this feature is brilliant),
it seems the text is slightly bolded. Not sure why.

Do you think this is caused by iOS SDK? because from single image perspective, I cannot see any difference, even the text is the same.

**Comment by liuxuan30** [comment]
![image](https://user-images.githubusercontent.com/4375169/65413184-759dac80-de23-11e9-85ae-5bdf15ec9c1e.png)
another image. not as obvious as above one, but still the same issue.

**Comment by reidmain** [comment]
Things like this are typically caused by changes in the iOS SDK. UIKit always has tons of subtle changes that require snapshot tests to be regenerated every time a major version is released.

If you have a small enough number of snapshots you should go through them to verify that the diffs have no major changes but otherwise you typically have to declare bankruptcy and simply regenerate all of your snapshots.
