### ISSUE TITLE
Color mismatch on iPhone8

### ISSUE THREAD

**Issue by victorBaro** [uber/ios-snapshot-test-case#37]
Hello, 

I am using your library and I generate the snapshots using xcodebuild in 4 different devices at once (iPhone8, 8Plus, SE and X).

After generating the 4 snapshots for each test, when I run the tests in xcode, some of them are failing. The diff is clearly not helping:
<img width="375" alt="diff_testcountryandprovincestate_iphone_375x667 2x" src="https://user-images.githubusercontent.com/994334/40133165-ccaf75fa-58f3-11e8-806d-d1b7392a8bcd.png">

Reference image:
<img width="375" alt="failed_testcountryandprovincestate_iphone_375x667 2x" src="https://user-images.githubusercontent.com/994334/40133173-d3b5c0de-58f3-11e8-982e-3774610e7a47.png">

I found [this issue](https://github.com/facebookarchive/ios-snapshot-test-case/issues/184) but it is not helping and I don't believe is the same problem. 

I have used the Digital Color Meter on the diff image and there are definitely parts of the image where the color differs from one pixel to another. Also, there is a bit of ghosting at the bottom (where the big blue button is).

This problem only appears on iPhone 8. It has something to do with colors. I have generated the reference images and run the test on the same machine, same simulator.

**Comment by alanzeino** [comment]
The fact that you're seeing the colour differ suggests to me either a simulator issue or GPU. Can you reset your simulator and see if that makes a difference?

You can also set a breakpoint in the test, and see if the colours are different there. I would recommend using the `visualize` command using Chisel, which will let you do `theButton visualize` in LLDB (where `theButton` represents the pointer to the button instance).

**Comment by victorBaro** [comment]
Thank you @alanzeino 
I have been working a bit more on this issue. Thank you for your suggestions.

There is a weird thing happening. As I said, I was launching the snapshot tests simultaneously in 4 devices using `xcodebuild` and specifying the different locations. Doing it this way, iPhone 8 (or 7) always fail.

However, if I only specify 1 location ("iPhone 8 simulator", for example), or if I generate the images directly from Xcode (in 1 device, obviously), the reference images are generated correctly and tests pass.

Any ideas?

**Comment by regnerjr** [comment]
@victorBaro I was inspired by the parallel testing info from WWDC 2018 and decide to try this too. 
I have the same setup as you, where I'm passing multiple simulators to Xcode build and some of them are failing with "ghosting" issues the same as you.

**Comment by victorBaro** [comment]
@regnerjr glad to hear I am not alone :D 

Out of curiosity.. how do you guys (in general) manage to create different snapshots (one per device "family" - normal, SE, Plus, X) if you are not using this method? Or you just create snapshots for 1 device in particular?

**Comment by acecilia** [comment]
@victorBaro At the moment I am having same issue: snapshots using Xcode are fine, but using xcodebuild and executing them in paralel results in differences. Something strange is going on.
About your question, I did not do it yet, but in my build server I have 5 agents (5 different macs), so I think I will run one device per agent to avoid this issue and run the tests faster.

**Comment by acecilia** [comment]
I confirmed that my tests in iPhone8 and iPhoneX with tolerance zero behave like:
- When running individually form Xcode, they pass.
- When running individually from command line (xcodebuild), they pass.
- When running at the same time using command line (xcodebuild with multiple destinations) iPhone8 pass, but iPhoneX does not pass, saying that images differ.

**Comment by acecilia** [comment]
@victorBaro from your tests in iPhone8, 8Plus, SE and X, can you confirm which devices fail when runnning in paralel? Can you confirm that running xcodebuild individually pass without problems?

**Comment by victorBaro** [comment]
@acecilia thank you for your comments. 

My case si similar tou yours but the device always failing is the iPhone8 and not the iPhoneX (only when running in parallel).

I have a basic script that runs tests in 2 steps:
- parallel iphoneX, SE and plus
- xcodebuild iPhone8 only

If I run the 2 steps in the above order, it fails. 
If I first run iPhone8, and then the rest in parallel, then everything works...

**Comment by alanzeino** [comment]
One thing I want to mention now that I've seen how you all are running your tests; running snapshot tests generated on one simulator device type on a different device type does not work and is not supported by the library. This also applies to the iOS version of the simulator — snapshots generated on iOS 10.3 with an iPhone 7 will likely fail when run on iOS 11.0 with an iPhone 7.

In the _device type_ case, this is because different device types can have different colour profiles that are invisible to the end user. For example, the iPhone 8 uses LCD technology while the iPhone X uses OLED, so Apple applies different profiles to each device type.

In the _iOS version_ case, this is because in general Apple tweaks stuff like line height and text aliasing in labels, kerning, etc.

The way to support this is to either;

1. Generate different snapshot files for each device type or iOS version. You can use the `agnosticOptions` bitmask to accomplish this.
2. Implement your own version of `FBSnapshotVerifyView()` that changes the view's frame for all the device types you want to test; 320x480 for iPhone 4/4s, 320x568 for iPhone 5/5s/5c, etc. This doesn't fully let you test the other device type (because you still run those snapshots on one simulator) but it does let you at least test how your view looks at different sizes.

If it helps I can add support for `2` to the library.

**Comment by aleksandergrzyb** [comment]
> Implement your own version of FBSnapshotVerifyView() that changes the view's frame for all the device types you want to test; 320x480 for iPhone 4/4s, 320x568 for iPhone 5/5s/5c, etc. This doesn't fully let you test the other device type (because you still run those snapshots on one simulator) but it does let you at least test how your view looks at different sizes.

This is what we currently do in our project. In order to mock specific devices we use modified version of [TraitController](https://github.com/kickstarter/ios-oss/blob/master/Kickstarter-iOS/TestHelpers/TraitController.swift) from Kickstarter. We also work on our own version of library where we would be able to mock all traits of device (not only screen size, but also size classes, layout margins etc.). We plan to open-source it, but I can't give any timeframe for that. Would be great to see those additions in ios-snapshot-test-case.

> In the iOS version case, this is because in general Apple tweaks stuff like line height and text aliasing in labels, kerning, etc.

Exactly. When we internally switch to new Xcode version we need to rerecord almost all snapshot reference images. Even for smaller upgrades such us from Xcode 9.3 to Xcode 9.4. Also we try to stick to the same device across iOS/Xcode updates (in our case it's iPhone 8).

**Comment by acecilia** [comment]
Thanks @alanzeino and @aleksandergrzyb, I did not know all those details. But seems this problem is not related with the iOS versions: I am running all the time iOS11.4.

I did further testing @victorBaro. To recall: I have my reference images taken using Xcode in each simulator (iPhone8 and iPhoneX), and zero tolerance. In addition to what I said:

> I confirmed that my tests in iPhone8 and iPhoneX with tolerance zero behave like:
> 
> - When running individually form Xcode, they pass.
> - When running individually from command line (xcodebuild), they pass.
> - When running at the same time using command line (xcodebuild with multiple destinations) iPhone8 pass, but iPhoneX does not pass, saying that images differ.

- Seems like when running at the same time using command line (xcodebuild with multiple destinations), the order of the destinations also affects: sometimes iPhone8 fails, other times iPhoneX fails, and I could not guess a pattern.

- Also, I realised that running the tests using xcodebuild individually, does not always succeed: at the moment running the tests like this fails for me:

```
xcodebuild \
  -workspace Project.xcworkspace \
  -scheme ProjectUITests \
  -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' \
  -derivedDataPath './testOutput' \
  test
```

- In addition, I open the iPhone8 simulator, and **without closing it** I run the tests, first using Xcode and then using xcodebuild. Running from Xcode succeeds, running from xcodebuild fails saying that images are different.

So, as a conclusion, looks like the only reliable way of running the simulators is from xcode :/

**Comment by acecilia** [comment]
Still looking into the issue. In my case what I am using this library for is explained [here](https://medium.com/@joesusnick/snapshot-xcui-testing-6a16c7ccd47b). I am taking a screenshot of the simulator using app.screenshot().image and passing it to ios-snapshot-test-case.

It seems that the screenshot differs in the borders of assets and shadows. For example, here there is one of the icons I am using, and in the right are the differences between a reference image and a failed image (in black the different pixels):

![captura de pantalla 2018-06-25 a las 0 56 12](https://user-images.githubusercontent.com/7938671/41824569-b3f60e28-7812-11e8-8e0b-2fd64e8f84a6.png)

A detail of the top border of the icon with the reference image on the left and the failed image in the right shows what is going on:

![captura de pantalla 2018-06-25 a las 0 40 55](https://user-images.githubusercontent.com/7938671/41824575-ca15ec8c-7812-11e8-87e1-de56a738cc69.png)

**Comment by victorBaro** [comment]
Hello @acecilia 

You are a life saver. That was it. Sorry it took me a while to test this, but exactly as you said, the problem goes away by specifying a different build folder for each simulator. 

I am closing this issue for now. It is not the best solution but I don’t think there is much that can be done besides that.

Thank you again!

**Comment by marcelofabri** [comment]
For future reference, I've filled http://openradar.appspot.com/44658414 (please dupe!) and there are some other workarounds listed there.
