### ISSUE TITLE
snapshot testing best practices

### ISSUE THREAD

**Issue by DavidTomic** [uber/ios-snapshot-test-case#54]
Hi,

I don't know where to ask, so I am asking it here.

I read all about snashot testing via websites and issues presented here.

There are many combinations how we can test our apps using this tool.

I've just started using this tool and it would be nice to here how are you using it and your best practices.

e.g. 
- Are you testing app for all popular iOS versions (10, 11 and 12).
- On which resolutions are you testing or which simulator devices are you using.
- Are you running tests via Xcode or xcodebuild.
- Are you using additional tools like FBSnapshotsViewer  https://github.com/Antondomashnev/FBSnapshotsViewer

Let me know your way of doing it, thank you.

**Comment by alexissan** [comment]
@DavidTomic I use this library in our my company and I wrote and article about the topic and could help you because I answered some of this questions with the solution that worked better for us. This is the link:
https://badootech.badoo.com/implementing-ui-in-ios-better-faster-and-it-scales-9788659e482

Let me know if you have questions about it! I hope it helps!

**Comment by DavidTomic** [comment]
@alexissan thank you for this article, it is very impressive and helpful.

It is a great idea to make snaphots only for the most popular device.

I suppose you have a lot of components but your snapshot folder is only ~11MB

I am wondering is there a way to make snaphots smaller. Because If I take a snapshot using iPhone X for view which has 375w x 180h in points, resulting snapshot than has 1125 x 540 pixels which is 60KB. So If I have e.g. 1000 snaphots that would be 60MB.

What is your process of resolving failure snaphots, do you use any tool for this.

Do you have issues after Xcode and iOS upgrades, e.g. you were testing on simulator with iOS 10, and after Xcode upgrade you now run tests on iOS 11 and here there is big posibility that many of test will fail. How do you manage this.

@alexissan thank you for your time.

**Comment by reidmain** [comment]
Hey there @DavidTomic 

> I am wondering is there a way to make snaphots smaller. Because If I take a snapshot using iPhone X for view which has 375w x 180h in points, resulting snapshot than has 1125 x 540 pixels which is 60KB. So If I have e.g. 1000 snaphots that would be 60MB.

Unfortunately this is a problem that always comes up with snapshot testing because Retina images are large by nature. Companies like Facebook and Uber get to the point where our snapshots take up hundreds of MBs of space. One solution is you could look into [Git Large File Storage](https://git-lfs.github.com/).

> What is your process of resolving failure snaphots, do you use any tool for this.

It is pretty much the same as debugging any issue with your code. Putting in a breakpoint and using [Xcode's view debugger](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html) or [Facebook's Chisel](https://github.com/facebook/chisel) to inspect your view hierarchy.

Also if you look at the console for a failed test you'll find something like
```
If you have [Kaleidoscope](https://www.kaleidoscopeapp.com/) installed you can run this command to see an image diff:
ksdiff "/Users/reid/ios-snapshot-test-case/FBSnapshotTestCaseDemo/FBSnapshotTestCaseDemoTests/FailedSnapshotImages/FBSnapshotTestCaseDemoTests.FBSnapshotTestCaseSwiftTest/reference_testExample@2x.png" "/Users/reid/ios-snapshot-test-case/FBSnapshotTestCaseDemo/FBSnapshotTestCaseDemoTests/FailedSnapshotImages/FBSnapshotTestCaseDemoTests.FBSnapshotTestCaseSwiftTest/failed_testExample@2x.png"
```
If you don't use Kaledioscope you can still use the absolute file paths printed to the console to open the images in other tools like Preview.

> Do you have issues after Xcode and iOS upgrades, e.g. you were testing on simulator with iOS 10, and after Xcode upgrade you now run tests on iOS 11 and here there is big posibility that many of test will fail. How do you manage this.

Yes all of the time. You can guarantee that Apple will always break something involving the UI when you jump major iOS version. You can manage this one of two ways:

1) When you jump to a new iOS version you regenerate all of the snapshots and manually check to see everything looks good.
2) Use `@property (readwrite, nonatomic, assign) FBSnapshotTestCaseFileNameIncludeOption fileNameOptions;` and ensure `FBSnapshotTestCaseFileNameIncludeOptionDevice` and `FBSnapshotTestCaseFileNameIncludeOptionOS` are turned on so you don't regenerate any snapshots but you create new ones that have the simulator and OS version embedded in the filenames.

Hopefully this answered your questions David but feel free to reopen the issue.
