### ISSUE TITLE
Ability to set reference and diff directories at runtime

### ISSUE THREAD

**Issue by daniel-beard** [uber/ios-snapshot-test-case#60]
With FBSnapshotTestCase, we used to be able to set the reference and diff directories at runtime, the current implementation allows only for compile time (#ifdef approach, or externally via ENV vars).

**Comment by daniel-beard** [comment]
Flexibility really. We use paths calculated from a source file location. FBSnapshotTestCase worked pretty well in this regard.

**Comment by alanzeino** [comment]
Can you point out which commit changed the behaviour you relied on? I didn't know that this was the case. Happy to add it back.

**Comment by reidmain** [comment]
I am going to close this issue since it has been inactive for over 6 months. @daniel-beard if there is a commit in the history of the repo that had this functionality please point it out and we'll look into adding it back. But as far as I can tell you always had to set the reference and diff directories via either a preprocessor macro or a environment variable.
