### ISSUE TITLE
Image file name changed and useless 32bit images after framework update

### ISSUE THREAD

**Issue by liuxuan30** [uber/ios-snapshot-test-case#78]
Hi there,

Not sure if you can see my comments in https://github.com/danielgindi/Charts/pull/3874, so I posted here again. sorry for any inconvenience. 
>the image file name pattern has been changed, such as from `testDefaultValues_iOS_375.0_667.0@2x.png` to `testDefaultValues_iOS_375_0_667_0@2x.png`
>note `375.0_667.0` to `375_0_667_0`
>there is a ReferenceImages_32 folder added, while we only have ReferenceImages_64.
>Since this seems caused by the test case framework update itself, I'm going to ask @alanzeino for a quick help: is it configurable so we don't have to change the name pattern? Can we disable 32bit images? I don't think we need a 32bit arch, iPhone 5 is long dead now. Basically I don't want to touch the images, it should work by itself.

**Comment by reidmain** [comment]
Sorry it has taken so long to respond to this @liuxuan30.

Regarding the change in the filename pattern I am actually quite surprised to hear that. We did add a `fileNameOptions` property to customize what was included but I was under the impression that it was backwards compatible. I apologize for the breaking change but I think regenerating the snapshots and having git recognize them as a move is probably the best thing.

The useless "ReferenceImages_32" folder was also mentioned here https://github.com/uber/ios-snapshot-test-case/issues/42 and I agree with you 100%. I also see you found the workaround of explicitly setting the suffixes to only contain "_64". https://github.com/uber/ios-snapshot-test-case/issues/42 also recommends changing the suffixes so that it only includes the architecture that is being testing and I don't see any reason why we can't make that change.

**Comment by liuxuan30** [comment]
ah ha, I already forgot I filed this :)
closing.  Thanks for replying! I think we are cool now. re-generate the image is the best workaround so far.
