### ISSUE TITLE
Does not work on Firebase Test Lab

### ISSUE THREAD

**Issue by brunoald** [uber/ios-snapshot-test-case#85]
Hi everyone. 

When working with [Firebase Test Lab](https://firebase.google.com/docs/test-lab), one should build locally a scheme for testing and then upload to it Firebase. 

When the app is compiled, the `$(SOURCE_ROOT)` property, which is interpolated into the `FB_REFERENCE_IMAGE_DIR` variable, becomes the absolute local path, like `/Users/yourname/path/to/project`. It means it won't work when the snapshot test runs in a different environment than the one it was built.

Is there a way to have a relative path in this `FB_REFERENCE_IMAGE_DIR` variable? This would solve the problem, I guess. I tried to use relative a path (e.g `../../Snapshots`) but I had no luck.  Since I'm not experienced with Objective-C, I found it difficult to look at the source code and figure out a solution.

**Comment by reidmain** [comment]
Unfortunately @brunoald I don't think this is possible. Because Firebase makes you compile a generic test runner everything seems to baked into it or pulled from the associated `.xctestrun` file. Even if you pass an environment variable into `xcodebuild` it seems that it is ignored for what is included in the `.xctestrun` file.

If we could get this to work how would Firebase have access to the reference images? Based on the instructions you linked Firebase seems to only want the `.xctestrun` file and build artifacts which doesn't include the reference images.

**Comment by reidmain** [comment]
I'm going to close this issue due to inactivity. Feel free to reopen if you have any follow up questions.
